services:
  api-gateway:
    build: .
    container_name: api-gateway
    ports:
      - "3000:3000"
    environment:
      - SERVICE=api-gateway
    depends_on:
      - user-service

  user-service:
    build: .
    container_name: user-service
    ports:
      - "50051:50051"
    environment:
      - SERVICE=user-service
    command: sh -c "node -r tsconfig-paths/register dist/user-service/src/app.js"